version: 2

registries:
    maven-github:
        type: maven-repository
        url: https://github-package-registry-mirror.gc.nav.no/cached/maven-release
        username: POSTMAN
        password: PAT

updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: daily

    - package-ecosystem: gradle
      directory: /
      schedule:
          interval: daily
      cooldown:
        default-days: 3
      groups:
        minor:
          applies-to: version-updates
          exclude-patterns:
            - "no.nav.aap*"
          update-types:
            - "minor"
            - "patch"

      registries:
          - maven-github
