name: Build and publish new release-version

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: write
            actions: read
            checks: write
            id-token: write
        name: Build & Test

        steps:
            -   uses: actions/checkout@v5
                with:
                    fetch-depth: 0
            -   name: Setup JDK
                uses: actions/setup-java@v5.0.0
                with:
                    distribution: 'temurin'
                    java-version: 25
            -   name: Setup Gradle for a wrapper project
                uses: gradle/actions/setup-gradle@v5
                with:
                    gradle-version: wrapper

            -   name: Build and run tests
                run: ./gradlew test --info
            -   uses: dorny/test-reporter@v2.1.1
                if: success() || failure()
                with:
                    name: test
                    path: "**/build/test-results/test/TEST-*.xml"
                    reporter: java-junit
                    token: ${{ secrets.GITHUB_TOKEN }}

            -   uses: paulhatch/semantic-version@v5.4.0
                id: tag
                with:
                    bump_each_commit: true
                    tag_prefix: ""

            -   id: notes
                run: |
                    randomDelimiter=${RANDOM}
                    text=$(git --no-pager log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h %s" | sed ':a;N;$!ba;s/\n/\n\n/g')
                    echo 'CHANGELOG<<$randomDelimiter' >> $GITHUB_OUTPUT
                    echo -e "$text" >> $GITHUB_OUTPUT
                    echo '$randomDelimiter' >> $GITHUB_OUTPUT
            -   name: Publish
                run: ./gradlew -Pversion=${{ steps.tag.outputs.version }} publish
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            -   uses: actions/create-release@v1.1.4
                id: create_release
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ steps.tag.outputs.version }}
                    release_name: ${{ steps.tag.outputs.version }}
                    body: |
                        Changes in this Release
                        ${{ steps.notes.outputs.CHANGELOG }}

            -   name: Genererer docs
                run: |
                    ./gradlew dokkaGenerate

            -   name: upload-artifact for docs
                uses: actions/upload-pages-artifact@v4
                with:
                    path: './build/dokka/html'

    deploy-pages:
        runs-on: ubuntu-latest
        needs: test
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.test.outputs.page_url }}

        steps:
            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4
